trigger: none

variables:
  vmImageName: 'ubuntu-latest'
  location: 'East US 2'
  templateFile: 'infra/main.bicep'
  csmParametersFile: 'infra/main.parameters.json'

name: $(date:yyyyMMdd)$(rev:.r)

jobs:

#################################################################
########### Creación de compoenntes de single tenant ############
#################################################################

- job: Job_1
  displayName: 'Aprovisionamiento de Infraestructura Single Tenant'
  
  pool:
    vmImage: $(vmImageName)

## Creacion de componentes en Azure
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Create Or Update Resource'
    inputs:
      deploymentScope: 'Subscription'
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      subscriptionId: $(subscriptionId)
      action: 'Create Or Update Resource Group'
      location: '$(location)'
      templateLocation: 'Linked artifact'
      csmFile: '$(templateFile)'
      csmParametersFile: '$(csmParametersFile)'
      overrideParameters: >
        -env $(env)
        -cliente $(cliente)
        -appServiceLinuxVersion $(appServiceLinuxVersion)
        -appServicePlanNameApi $(appServicePlanName)
        -StorageSku $(storageSku)
        -storageAccesTier $(storageAccesTier)
      deploymentMode: 'Incremental'
      deploymentName: 'DeployPipelineTemplate'

#################################################################
########### configuraciones a nivel de base de datos ############
#################################################################


